args: ['python3', 'tulip.py', './tests/compiler_errors/const_redef_const.tlp']
-------- stdout ----------
--------------------------
-------- stderr ----------
./tests/compiler_errors/const_redef_const.tlp:2:9 [ERROR]: Redefinition of `foo`. Previously defined here: ./tests/compiler_errors/const_redef_const.tlp:1:5
--------------------------
exit code: 1
